### ISSUE TITLE
Error When Starting

### ISSUE THREAD

**Issue by dacartier** [DracoR22/handi-cat_wallet-tracker#2]
This is the following error code I receive when reaching the last step. I've attempted rebuilding 6x, installing dependencies manually and still won't work.

bigint: Failed to load bindings, pure JS will be used (try npm run rebuild?)
C:\Users\Dylan\handi-cat_wallet-tracker\node_modules\.pnpm\@solana+web3.js@1.94.0\node_modules\@solana\web3.js\lib\index.cjs.js:4456
    throw new TypeError('Endpoint URL must start with `http:` or `https:`.');
    ^

TypeError: Endpoint URL must start with `http:` or `https:`.
    at assertEndpointUrl (C:\Users\Dylan\handi-cat_wallet-tracker\node_modules\.pnpm\@solana+web3.js@1.94.0\node_modules\@solana\web3.js\lib\index.cjs.js:4456:11)
    at new Connection (C:\Users\Dylan\handi-cat_wallet-tracker\node_modules\.pnpm\@solana+web3.js@1.94.0\node_modules\@solana\web3.js\lib\index.cjs.js:6044:25)
    at Object.<anonymous> (C:\Users\Dylan\handi-cat_wallet-tracker\dist\src\providers\solana.js:15:22)
    at Module._compile (node:internal/modules/cjs/loader:1480:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1287:32)
    at Module._load (node:internal/modules/cjs/loader:1103:12)
    at Module.require (node:internal/modules/cjs/loader:1310:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\Dylan\handi-cat_wallet-tracker\dist\src\lib\track-wallets.js:20:18)
    at Module._compile (node:internal/modules/cjs/loader:1480:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1287:32)
    at Module._load (node:internal/modules/cjs/loader:1103:12)
    at Module.require (node:internal/modules/cjs/loader:1310:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (C:\Users\Dylan\handi-cat_wallet-tracker\dist\src\bot\commands\add-command.js:17:25)
    at Module._compile (node:internal/modules/cjs/loader:1480:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1564:10)
    at Module.load (node:internal/modules/cjs/loader:1287:32)
    at Module._load (node:internal/modules/cjs/loader:1103:12)
    at Module.require (node:internal/modules/cjs/loader:1310:19)

Node.js v22.1.0
 ELIFECYCLE  Command failed with exit code 1.

**Comment by DracoR22** [comment]
Hi, make sure you add an rpc url in src/providers/solana.ts file or you can
just use SOLANA_NETWORK instead of the one I currently have, your
connection should look like:

 export const connection = new Connection(SOLANA_NETWORK, 'confirmed')

**Comment by dacartier** [comment]
Thank you for the reply, that actually managed to fix it and get the server running.

My only question now is this. My server is running via localhost, my webhook is deployed but nothing else is happening. My telegram bot is nonresponsive and I can't figure out how to go from where I am in the development to where your handi-cat bot is on telegram. I guess my question is moreso: "What do I do now that the server is running"

I really appreciate all of your help and time developing this software. If we can get this up and running I will gladly tip you some SOL

________________________________

**Comment by DracoR22** [comment]
Glad it worked!, now if you are running the bot in localhost you should use
polling method instead of webhook, so go to src/providers/telegram.ts and
comment out everything under line 15, then uncomment line 13, this will
change webhook method to polling.

**Comment by dacartier** [comment]
What is the difference between running the boy as localhost vs webhook? How would you go about setting up the alternative?

________________________________

**Comment by DracoR22** [comment]
Use polling whenever you are running it locally and change it to webhook
once you deploy it on a server, you can still use polling when its deployed
but changing to webhook is a better practice
